# Generated by Django 4.2 on 2023-08-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='jins',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
